name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  REGION: us-central1
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      # Clean Terraform local state & init
      - name: Terraform Init
        run: |
          cd infrastructure
          rm -rf .terraform .terraform.lock.hcl backend.tf
          terraform init

      # Ensure GCS bucket for Terraform remote state exists
      - name: Ensure State Bucket Exists
        run: |
          STATE_BUCKET="${PROJECT_ID}-tfstate-insight_agent"
          if ! gsutil ls -b gs://$STATE_BUCKET >/dev/null 2>&1; then
            echo "Creating state bucket: $STATE_BUCKET"
            gsutil mb -p $PROJECT_ID -l $REGION -b on gs://$STATE_BUCKET
          else
            echo "State bucket already exists."
          fi

      # Import state bucket into Terraform state & enable APIs
      - name: Bootstrap Remote State
        run: |
          cd infrastructure
          echo "$GOOGLE_CREDENTIALS" > "$HOME/key.json"

          if ! terraform state list | grep -q google_storage_bucket.tf_state; then
            terraform import \
              -var="credentials_file=$HOME/key.json" \
              -var="project_id=$PROJECT_ID" \
              google_storage_bucket.tf_state "${PROJECT_ID}-tfstate-insight_agent"
          fi

          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="credentials_file=$HOME/key.json" \
            -target=google_storage_bucket.tf_state \
            -target=google_project_service.required_apis

      # Switch to remote backend
      - name: Configure Remote Backend
        run: |
          cd infrastructure
          STATE_BUCKET="${PROJECT_ID}-tfstate-insight_agent"
          cat > backend.tf <<EOF
          terraform {
            backend "gcs" {
              bucket = "$STATE_BUCKET"
              prefix = "terraform/state"
            }
          }
          EOF
          rm -rf .terraform .terraform.lock.hcl
          yes | terraform init -migrate-state

      # Authenticate Docker for Artifact Registry
      - name: Authenticate Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # Build & Push Docker image
      - name: Build and Push Docker Image
        run: |
          cd app
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/insight-agent/insight-agent:$GITHUB_SHA .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/insight-agent/insight-agent:$GITHUB_SHA

      # Deploy infrastructure
      - name: Deploy Infrastructure
        run: |
          cd infrastructure
          
          # 1. Initialize with empty state if none exists
          if [ ! -f terraform.tfstate ]; then
            echo '{"version": 4, "terraform_version": "1.6.6", "serial": 1, "lineage": "00000000-0000-0000-0000-000000000000", "outputs": {}, "resources": []}' > terraform.tfstate
          fi
          
          # 2. Create temporary override file
          cat > override.tf <<EOF
          resource "google_storage_bucket" "tf_state" {
            count = 0 # This prevents creation
          }
          
          resource "google_artifact_registry_repository" "insight_agent" {
            count = 0 # This prevents creation
          }
          
          resource "google_service_account" "insight_agent" {
            count = 0 # This prevents creation
          }
          EOF
          
          # 3. Initialize Terraform
          terraform init
          
          # 4. Import existing resources if they exist (silent)
          terraform import google_storage_bucket.tf_state[0] "${PROJECT_ID}-tfstate-insight_agent" 2>/dev/null || true
          terraform import google_artifact_registry_repository.insight_agent[0] "projects/${PROJECT_ID}/locations/us-central1/repositories/insight-agent" 2>/dev/null || true
          terraform import google_service_account.insight_agent[0] "projects/${PROJECT_ID}/serviceAccounts/insight-agent-sa@${PROJECT_ID}.iam.gserviceaccount.com" 2>/dev/null || true
          
          # 5. Apply only Cloud Run resources
          terraform apply -auto-approve \
            -state=terraform.tfstate \
            -var="project_id=$PROJECT_ID" \
            -var="credentials_file=$HOME/key.json" \
            -var="image_tag=$GITHUB_SHA" \
            -target=google_cloud_run_service.insight_agent \
            -target=google_cloud_run_service_iam_member.public_access \
            -refresh=false \
            -lock=false
          
          # 6. Clean up override
          rm override.tf
          
          # 7. Push state to remote backend if configured
          if [ -f backend.tf ]; then
            terraform init -reconfigure
            terraform state push terraform.tfstate
          fi
            
      # Verify deployment
      - name: Verify Deployment
        run: |
          SERVICE_URL=$(cd infrastructure && terraform output -raw cloud_run_url)
          curl -s $SERVICE_URL/analyze -H "Content-Type: application/json" \
            -d '{"text":"Testing deployment"}' | jq .
